package prebot.brain.stratgy.enemy;

public enum EnemyStrategyOld {
	
//	public enum EnemyStrategyZerg {
//		ZERGBASIC, ZERGBASIC_HYDRAWAVE, ZERGBASIC_HYDRAMUTAL, ZERGBASIC_LINGHYDRA, ZERGBASIC_LINGMUTAL, ZERGBASIC_LINGULTRA, ZERGBASIC_MUTAL, ZERGBASIC_MUTALMANY, ZERGBASIC_ULTRA // ZERGBASIC_GIFTSET,
//	}
//
//	public enum EnemyStrategyProtoss {
//		PROTOSSBASIC, PROTOSSBASIC_CARRIER, PROTOSSBASIC_DOUBLEPHOTO
//	}
//
//	public enum EnemyStrategyTerran {
//		TERRANBASIC, TERRANBASIC_BIONIC, TERRANBASIC_MECHANIC, TERRANBASIC_MECHANICWITHWRAITH, TERRANBASIC_MECHANICAFTER, TERRANBASIC_BATTLECRUISER // ,terranBasic_ReverseRush
//	}
//
//	public enum EnemyStrategyCommon {
//		ATTACKISLAND
//	}
//
//	public enum EnemyExStrategyZerg {
//		ZERGEXCEPTION_FASTLURKER
//		// ,ZERGEXCEPTION_GUARDIAN
//		// ,ZERGEXCEPTION_NONGBONG
//		, ZERGEXCEPTION_ONLYLING, ZERGEXCEPTION_PREPARELURKER
//		// ,ZERGEXCEPTION_REVERSERUSH
//		, ZERGEXCEPTION_HIGHTECH
//	}
//
//	public enum EnemyExStrategyProtoss {
//		// ,PROTOSSEXCEPTION_CARRIERMANY
//		PROTOSSEXCEPTION_DARK
//		// ,PROTOSSEXCEPTION_REAVER
//		, PROTOSSEXCEPTION_SCOUT, PROTOSSEXCEPTION_SHUTTLE
//		// ,PROTOSSEXCEPTION_SHUTTLEMIX
//		, PROTOSSEXCEPTION_READYTOZEALOT, PROTOSSEXCEPTION_ZEALOTPUSH, PROTOSSEXCEPTION_READYTODRAGOON, PROTOSSEXCEPTION_DRAGOONPUSH, PROTOSSEXCEPTION_PHOTONRUSH, PROTOSSEXCEPTION_DOUBLENEXUS, PROTOSSEXCEPTION_ARBITER
//	}
//
//	public enum EnemyExStrategyTerran {
//		// ,TERRANEXCEPTION_CHEESERUSH
//		// ,TERRANEXCEPTION_NUCLEAR
//		TERRANEXCEPTION_WRAITHCLOAK,
//	} // INIT예외 전략 나열, 예외가 아닐때는 무조건 Init 으로
}
