package prebot.strategy.analyse;

public class Clue {
	
	public static enum ClueType {
		// PROTOSS
		PROTOSS_GAS, FAST_GATE, FAST_NEXSUS, FAST_FORGE, FAST_CANNON, FAST_CORE,
		
		// ZERG
		ZERG_GAS, POOL, POOL_ASSUME, DOUBLE_HATCH,
		LAIR, SPIRE, HYDRADEN,
		
		// TERRAN
		TERRAN_GAS, FAST_BARRACK, FAST_COMMAND,
	}

	public static enum ClueInfo {
		// PROTOSS
		ASSIMILATOR_FAST(ClueType.PROTOSS_GAS),
		ASSIMILATOR_LATE(ClueType.PROTOSS_GAS),
		NO_ASSIMILATOR(ClueType.PROTOSS_GAS),
		
		FORGE_FAST_IN_EXPANSION(ClueType.FAST_FORGE),
		FORGE_FAST_IN_BASE(ClueType.FAST_FORGE),
		FORGE_FAST_SOMEWHERE(ClueType.FAST_FORGE),
		
		CANNON_FAST_IN_EXPANSION(ClueType.FAST_CANNON),
		CANNON_FAST_IN_BASE(ClueType.FAST_CANNON),
		CANNON_FAST_SOMEWHERE(ClueType.FAST_CANNON),
		
		GATE_NOT_FOUND(ClueType.FAST_GATE),
		GATE_FAST_ONE(ClueType.FAST_GATE),
		GATE_FAST_TWO(ClueType.FAST_GATE),
		GATE_ONE(ClueType.FAST_GATE),
		GATE_TWO(ClueType.FAST_GATE),
		
		CORE_FAST(ClueType.FAST_CORE),
		
		NEXSUS_FASTEST_DOUBLE(ClueType.FAST_NEXSUS),
		NEXSUS_FAST_DOUBLE(ClueType.FAST_NEXSUS),
		NEXSUS_NOT_DOUBLE(ClueType.FAST_NEXSUS),
		

		// ZERG
		EXTRACTOR_9DRONE(ClueType.ZERG_GAS),
		EXTRACTOR_OVERPOOL(ClueType.ZERG_GAS),
		EXTRACTOR_2HAT(ClueType.ZERG_GAS),
		EXTRACTOR_LATE(ClueType.ZERG_GAS),
		NO_EXTRACTOR(ClueType.ZERG_GAS),
		
		POOL_9DRONE_UNDER(ClueType.POOL_ASSUME),
		POOL_OVERPOOL_UNDER(ClueType.POOL_ASSUME),
		
		POOL_5DRONE(ClueType.POOL),
		POOL_9DRONE(ClueType.POOL),
		POOL_OVERPOOL(ClueType.POOL),
		POOL_2HAT(ClueType.POOL),
		NO_POOL(ClueType.POOL),
		
		DOUBLE_HATCH_12HAT(ClueType.DOUBLE_HATCH),
		DOUBLE_HATCH_OVERPOOL(ClueType.DOUBLE_HATCH),
		DOUBLE_HATCH_9DRONE(ClueType.DOUBLE_HATCH),
		DOUBLE_HATCH_LATE(ClueType.DOUBLE_HATCH),
		TWIN_HATCH(ClueType.DOUBLE_HATCH),

		NO_LAIR(ClueType.LAIR),
		LAIR_INCOMPLETE(ClueType.LAIR),
		LAIR_COMPLETE(ClueType.LAIR),

		HYDRADEN_FASTEST(ClueType.HYDRADEN),
		HYDRADEN_NO_LAIR(ClueType.HYDRADEN),
		HYDRADEN_TWO_HATCH(ClueType.HYDRADEN),
		HYDRADEN(ClueType.HYDRADEN),

		SPIRE_1HAT(ClueType.SPIRE),
		SPIRE_2HAT(ClueType.SPIRE),
		SPIRE_3HAT(ClueType.SPIRE),
		SPIRE(ClueType.SPIRE),
		

		// TERRAN
		REFINERY_FAST(ClueType.TERRAN_GAS),
		REFINERY_LATE(ClueType.TERRAN_GAS),
		NO_REFINERY(ClueType.TERRAN_GAS),
		
		BARRACK_NOT_FOUND(ClueType.FAST_BARRACK),
		BARRACK_FAST_ONE(ClueType.FAST_BARRACK),
		BARRACK_FAST_TWO(ClueType.FAST_BARRACK),
		BARRACK_ONE(ClueType.FAST_BARRACK),
		BARRACK_TWO(ClueType.FAST_BARRACK),
		
		COMMAND_FASTEST_DOUBLE(ClueType.FAST_COMMAND),
		COMMAND_FAST_DOUBLE(ClueType.FAST_COMMAND),
		
		
		DUMMY(ClueType.POOL);
		
		private ClueInfo(ClueType type) {
			this.type = type;
		}
		public ClueType type;
	}
}
