package prebot.strategy.analyse;

public class Clue {
	
	public static enum ClueType {
		// PROTOSS
		PROTOSS_GAS, FAST_GATE, FAST_NEXSUS, FAST_FORGE, FAST_CANNON, FAST_CORE,
		FAST_DRAGOON_RANGE, FAST_ADUN, FAST_TEMPLAR_ARCH, FAST_ROBO, FAST_ROBO_SUPPORT, FAST_OB, STARGATE,
		FLEET_BEACON,
		
		FAST_ZEALOT, FAST_DRAGOON, FAST_DARK, FAST_SHUTTLE, FAST_OBSERVER, FAST_REAVER,
		
		// ZERG
		ZERG_GAS, POOL, POOL_ASSUME, DOUBLE_HATCH,
		FAST_LAIR, LAIR_STATUS, SPIRE, HYDRADEN,
		
		FAST_ZERGLING,
		FAST_HYDRA, FAST_LURKER, FAST_MUTAL,
		
		// TERRAN
		TERRAN_GAS, FAST_BARRACK, FAST_COMMAND, FAST_ACADEMY,
		FAST_FACTORY, FAST_STARPORT, FAST_ARMORY,
		
		FAST_MARINE, MEDIC, FIREBAT,
		FAST_VULTURE, FAST_TANK, FAST_GOLIATH, FAST_WRAITH,
		
		DUMMY,
	}

	public static enum ClueInfo {
		// PROTOSS
		ASSIMILATOR_FAST(ClueType.PROTOSS_GAS),
		ASSIMILATOR_LATE(ClueType.PROTOSS_GAS),
		NO_ASSIMILATOR(ClueType.PROTOSS_GAS),
		
		FORGE_FAST_IN_EXPANSION(ClueType.FAST_FORGE),
		FORGE_FAST_IN_BASE(ClueType.FAST_FORGE),
		FORGE_FAST_SOMEWHERE(ClueType.FAST_FORGE),
		
		CANNON_FAST_IN_EXPANSION(ClueType.FAST_CANNON),
		CANNON_FAST_IN_BASE(ClueType.FAST_CANNON),
		CANNON_FAST_SOMEWHERE(ClueType.FAST_CANNON),
		
		GATE_NOT_FOUND(ClueType.FAST_GATE),
		GATE_FAST_ONE(ClueType.FAST_GATE),
		GATE_FAST_TWO(ClueType.FAST_GATE),
		GATE_ONE(ClueType.FAST_GATE),
		GATE_TWO(ClueType.FAST_GATE),
		
		CORE_FAST(ClueType.FAST_CORE),
		CORE_FOUND(ClueType.FAST_CORE),
		
		DRAGOON_RANGE_FAST(ClueType.FAST_DRAGOON_RANGE),
		
		ADUN_FAST(ClueType.FAST_ADUN),
		TEMPLAR_ARCH_FAST(ClueType.FAST_TEMPLAR_ARCH),
		
		ROBO_FAST(ClueType.FAST_ROBO),
		ROBO_SUPPORT_FAST(ClueType.FAST_ROBO_SUPPORT),
		OBSERVERTORY_FAST(ClueType.FAST_OB),
		
		STARGATE_ONEGATE_FAST(ClueType.STARGATE),
		STARGATE_DOUBLE_FAST(ClueType.STARGATE),
		STARGATE_FOUND(ClueType.STARGATE),
		
		FAST_FLEET_BEACON(ClueType.FLEET_BEACON),
		FLEET_BEACON_FOUND(ClueType.FLEET_BEACON),
		
		NEXSUS_FASTEST_DOUBLE(ClueType.FAST_NEXSUS),
		NEXSUS_FAST_DOUBLE(ClueType.FAST_NEXSUS),
		NEXSUS_NOT_DOUBLE(ClueType.FAST_NEXSUS),

		FAST_ONE_ZEALOT(ClueType.FAST_ZEALOT),
		FAST_THREE_ZEALOT(ClueType.FAST_ZEALOT),
		FAST_DRAGOON(ClueType.FAST_DRAGOON),
		FAST_DARK(ClueType.FAST_DARK),
		FAST_SHUTTLE(ClueType.FAST_SHUTTLE),
		FAST_OBSERVER(ClueType.FAST_OBSERVER),
		FAST_REAVER(ClueType.FAST_REAVER),
		
		// ZERG
		EXTRACTOR_9DRONE(ClueType.ZERG_GAS),
		EXTRACTOR_OVERPOOL(ClueType.ZERG_GAS),
		EXTRACTOR_2HAT(ClueType.ZERG_GAS),
		EXTRACTOR_LATE(ClueType.ZERG_GAS),
		NO_EXTRACTOR(ClueType.ZERG_GAS),
		
		POOL_9DRONE_UNDER(ClueType.POOL_ASSUME),
		POOL_OVERPOOL_UNDER(ClueType.POOL_ASSUME),
		
		POOL_5DRONE(ClueType.POOL),
		POOL_9DRONE(ClueType.POOL),
		POOL_OVERPOOL(ClueType.POOL),
		POOL_2HAT(ClueType.POOL),
		LATE_POOL(ClueType.POOL),
		
		DOUBLE_HATCH_12HAT(ClueType.DOUBLE_HATCH),
		DOUBLE_HATCH_OVERPOOL(ClueType.DOUBLE_HATCH),
		DOUBLE_HATCH_9DRONE(ClueType.DOUBLE_HATCH),
		DOUBLE_HATCH_LATE(ClueType.DOUBLE_HATCH),
		TWIN_HATCH(ClueType.DOUBLE_HATCH),

		LAIR_1HAT_FAST(ClueType.FAST_LAIR),
		LAIR_2HAT_FAST(ClueType.FAST_LAIR),
		LAIR_3HAT_FAST(ClueType.FAST_LAIR),
		
		NO_LAIR(ClueType.LAIR_STATUS),
		LAIR_INCOMPLETE(ClueType.LAIR_STATUS),
		LAIR_COMPLETE(ClueType.LAIR_STATUS),

		HYDRADEN_BEFORE_LAIR_START(ClueType.HYDRADEN),
		HYDRADEN_BEFORE_LAIR_COMPLETE(ClueType.HYDRADEN),
		HYDRADEN(ClueType.HYDRADEN),

		FAST_SPIRE(ClueType.SPIRE),
		SPIRE(ClueType.SPIRE),

		FAST_OVERTEN_ZERGLING(ClueType.FAST_ZERGLING),
		FAST_EIGHT_ZERGLING(ClueType.FAST_ZERGLING),
		FAST_SIX_ZERGLING(ClueType.FAST_ZERGLING),
		
		FAST_HYDRA(ClueType.FAST_HYDRA),
		FIVE_MANY_HYDRA(ClueType.FAST_HYDRA),
		THREE_MANY_HYDRA(ClueType.FAST_HYDRA),
		FAST_LURKER(ClueType.FAST_LURKER),
		FAST_MUTAL(ClueType.FAST_MUTAL),

		// TERRAN
		REFINERY_FAST(ClueType.TERRAN_GAS),
		REFINERY_LATE(ClueType.TERRAN_GAS),
		NO_REFINERY(ClueType.TERRAN_GAS),
		
		BARRACK_NOT_FOUND(ClueType.FAST_BARRACK),
		BARRACK_FAST_ONE(ClueType.FAST_BARRACK),
		BARRACK_FAST_TWO(ClueType.FAST_BARRACK),
		BARRACK_FASTEST_TWO(ClueType.FAST_BARRACK),
		BARRACK_ONE(ClueType.FAST_BARRACK),
		BARRACK_TWO(ClueType.FAST_BARRACK),
		
		ACADEMY_FAST(ClueType.FAST_ACADEMY),
		ACADEMY_FOUND(ClueType.FAST_ACADEMY),
		
		ARMORY_FAST(ClueType.FAST_ARMORY),
		ARMORY_FOUND(ClueType.FAST_ARMORY),
		
		FACTORY_NOT_FOUND(ClueType.FAST_FACTORY),
		FACTORY_FAST_ONE(ClueType.FAST_FACTORY),
		FACTORY_FAST_TWO(ClueType.FAST_FACTORY),
		FACTORY_ONE(ClueType.FAST_FACTORY),
		FACTORY_TWO(ClueType.FAST_FACTORY),
		
		STARPORT_FAST_ONE(ClueType.FAST_STARPORT),
		STARPORT_FAST_TWO(ClueType.FAST_STARPORT),
		STARPORT_ONE(ClueType.FAST_STARPORT),
		STARPORT_TWO(ClueType.FAST_STARPORT),
		
		COMMAND_FASTEST_DOUBLE(ClueType.FAST_COMMAND),
		COMMAND_FAST_DOUBLE(ClueType.FAST_COMMAND),
		COMMAND_FAC_DOUBLE(ClueType.FAST_COMMAND),
		
		FAST_SIX_MARINE(ClueType.FAST_MARINE),
		FAST_FOUR_MARINE(ClueType.FAST_MARINE),
		FAST_TWO_MARINE(ClueType.FAST_MARINE),
		
		FAST_SIX_VULTURE(ClueType.FAST_VULTURE),
		FAST_FOUR_VULTURE(ClueType.FAST_VULTURE),
		FAST_TWO_VULTURE(ClueType.FAST_VULTURE),
		
		FAST_MEDIC(ClueType.MEDIC),
		MEDIC_FOUND(ClueType.MEDIC),
		FAST_FIREBAT(ClueType.FIREBAT),
		FIREBAT_FOUND(ClueType.FIREBAT),
		
		FAST_ONE_TANK(ClueType.FAST_TANK),
		FAST_TWO_TANK(ClueType.FAST_TANK),
		FAST_THREE_TANK(ClueType.FAST_TANK),
		TANK_FOUND(ClueType.FAST_TANK),
		
		FAST_ONE_GOLIATH(ClueType.FAST_GOLIATH),
		FAST_TWO_GOLIATH(ClueType.FAST_GOLIATH),
		FAST_THREE_GOLIATH(ClueType.FAST_GOLIATH),
		GOLIATH_FOUND(ClueType.FAST_GOLIATH),
		
		FAST_ONE_WRAITH(ClueType.FAST_WRAITH),
		FAST_TWO_WRAITH(ClueType.FAST_WRAITH),
		FAST_THREE_WRAITH(ClueType.FAST_WRAITH),
		WRAITH_FOUND(ClueType.FAST_WRAITH),
		
		DUMMY(ClueType.DUMMY);
		
		private ClueInfo(ClueType type) {
			this.type = type;
		}
		public ClueType type;
	}
}
