package prebot.strategy.analyse;

public class Clue {
	
	public static enum ClueType {
		// PROTOSS
		PROTOSS_GAS, FAST_GATE, FAST_NEXSUS, FAST_FORGE, FAST_CANNON, FAST_CORE,
		FAST_DRAGOON_RANGE, FAST_ADUN, FAST_TEMPLAR_ARCH, FAST_ROBO, FAST_ROBO_SUPPORT, FAST_OB, FAST_STARGATE,
		
		// ZERG
		ZERG_GAS, POOL, POOL_ASSUME, DOUBLE_HATCH,
		FAST_LAIR, LAIR_STATUS, SPIRE, HYDRADEN,
		
		// TERRAN
		TERRAN_GAS, FAST_BARRACK, FAST_COMMAND,
	}

	public static enum ClueInfo {
		// PROTOSS
		ASSIMILATOR_FAST(ClueType.PROTOSS_GAS),
		ASSIMILATOR_LATE(ClueType.PROTOSS_GAS),
		NO_ASSIMILATOR(ClueType.PROTOSS_GAS),
		
		FORGE_FAST_IN_EXPANSION(ClueType.FAST_FORGE),
		FORGE_FAST_IN_BASE(ClueType.FAST_FORGE),
		FORGE_FAST_SOMEWHERE(ClueType.FAST_FORGE),
		
		CANNON_FAST_IN_EXPANSION(ClueType.FAST_CANNON),
		CANNON_FAST_IN_BASE(ClueType.FAST_CANNON),
		CANNON_FAST_SOMEWHERE(ClueType.FAST_CANNON),
		
		GATE_NOT_FOUND(ClueType.FAST_GATE),
		GATE_FAST_ONE(ClueType.FAST_GATE),
		GATE_FAST_TWO(ClueType.FAST_GATE),
		GATE_ONE(ClueType.FAST_GATE),
		GATE_TWO(ClueType.FAST_GATE),
		
		CORE_FAST(ClueType.FAST_CORE),
		DRAGOON_RANGE_FAST(ClueType.FAST_DRAGOON_RANGE),
		
		ADUN_FAST(ClueType.FAST_ADUN),
		TEMPLAR_ARCH_FAST(ClueType.FAST_TEMPLAR_ARCH),
		
		ROBO_FAST(ClueType.FAST_ROBO),
		ROBO_SUPPORT_FAST(ClueType.FAST_ROBO_SUPPORT),
		OBSERVER_FAST(ClueType.FAST_OB),
		
		STARGATE_ONEGATE_FAST(ClueType.FAST_STARGATE),
		STARGATE_DOUBLE_FAST(ClueType.FAST_STARGATE),
		
		NEXSUS_FASTEST_DOUBLE(ClueType.FAST_NEXSUS),
		NEXSUS_FAST_DOUBLE(ClueType.FAST_NEXSUS),
		NEXSUS_NOT_DOUBLE(ClueType.FAST_NEXSUS),
		

		// ZERG
		EXTRACTOR_9DRONE(ClueType.ZERG_GAS),
		EXTRACTOR_OVERPOOL(ClueType.ZERG_GAS),
		EXTRACTOR_2HAT(ClueType.ZERG_GAS),
		EXTRACTOR_LATE(ClueType.ZERG_GAS),
		NO_EXTRACTOR(ClueType.ZERG_GAS),
		
		POOL_9DRONE_UNDER(ClueType.POOL_ASSUME),
		POOL_OVERPOOL_UNDER(ClueType.POOL_ASSUME),
		
		POOL_5DRONE(ClueType.POOL),
		POOL_9DRONE(ClueType.POOL),
		POOL_OVERPOOL(ClueType.POOL),
		POOL_2HAT(ClueType.POOL),
		NO_POOL(ClueType.POOL),
		
		DOUBLE_HATCH_12HAT(ClueType.DOUBLE_HATCH),
		DOUBLE_HATCH_OVERPOOL(ClueType.DOUBLE_HATCH),
		DOUBLE_HATCH_9DRONE(ClueType.DOUBLE_HATCH),
		DOUBLE_HATCH_LATE(ClueType.DOUBLE_HATCH),
		TWIN_HATCH(ClueType.DOUBLE_HATCH),

		LAIR_1HAT_FAST(ClueType.FAST_LAIR),
		LAIR_2HAT_FAST(ClueType.FAST_LAIR),
		LAIR_3HAT_FAST(ClueType.FAST_LAIR),
		
		NO_LAIR(ClueType.LAIR_STATUS),
		LAIR_INCOMPLETE(ClueType.LAIR_STATUS),
		LAIR_COMPLETE(ClueType.LAIR_STATUS),

		HYDRADEN_BEFORE_LAIR_START(ClueType.HYDRADEN),
		HYDRADEN_BEFORE_LAIR_COMPLETE(ClueType.HYDRADEN),
		HYDRADEN(ClueType.HYDRADEN),

		FAST_SPIRE(ClueType.SPIRE),
		SPIRE(ClueType.SPIRE),
		

		// TERRAN
		REFINERY_FAST(ClueType.TERRAN_GAS),
		REFINERY_LATE(ClueType.TERRAN_GAS),
		NO_REFINERY(ClueType.TERRAN_GAS),
		
		BARRACK_NOT_FOUND(ClueType.FAST_BARRACK),
		BARRACK_FAST_ONE(ClueType.FAST_BARRACK),
		BARRACK_FAST_TWO(ClueType.FAST_BARRACK),
		BARRACK_ONE(ClueType.FAST_BARRACK),
		BARRACK_TWO(ClueType.FAST_BARRACK),
		
		COMMAND_FASTEST_DOUBLE(ClueType.FAST_COMMAND),
		COMMAND_FAST_DOUBLE(ClueType.FAST_COMMAND),
		
		
		DUMMY(ClueType.POOL);
		
		private ClueInfo(ClueType type) {
			this.type = type;
		}
		public ClueType type;
	}
}
